/*
  This is a web mock class,  used for the testing of Dosespot stuff....or at least it will be if I'm awake enough to write this properly
  
  Okay---after looking into this,  I probably don't need a web mock.  The piece I'm using is just the Dosespot class and that appear to be using HTTP request instead of the SOAP stuff.  
  I'm leaving this here in case we ever need to pull the Soap stuff over.
*/
@isTest
global class web_mock_dosespot {
  
}